title: CampusPulse Report
description: Report things to ServiceNow.

servicenow_domain: "help.rit.edu"
repository_url: "https://github.com/CampusPulse/report"

baseurl: ""

exclude: ["Gemfile", "Gemfile.lock"]
